
export class Admin {
  id?: number; // Optional, auto-generated by backend
  name: string = '';
  email: string = '';
  mobileNumber: string = '';
  username: string = '';
  password: string = '';
  confirmPassword: string = '';
}
